/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#255dad",
        "surface-dim": "#c7dde9",
        "on-secondary-fixed": "#002204",
        "on-primary-fixed": "#001b3f",
        surface: "#f3faff",
        "on-secondary-container": "#217128",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#004f53",
        "error-container": "#ffdad6",
        "surface-container-low": "#e6f6ff",
        "secondary-container": "#a0f399",
        primary: "#001d44",
        "secondary-fixed-dim": "#88d982",
        "on-surface-variant": "#43474f",
        secondary: "#1b6d24",
        "on-primary": "#ffffff",
        "secondary-fixed": "#a3f69c",
        "inverse-primary": "#abc7ff",
        "surface-variant": "#cfe6f2",
        "on-secondary": "#ffffff",
        "surface-container": "#dbf1fe",
        outline: "#737780",
        tertiary: "#002325",
        "surface-container-highest": "#cfe6f2",
        "on-tertiary-container": "#5ea7ab",
        "on-surface": "#071e27",
        error: "#ba1a1a",
        "primary-fixed": "#d7e2ff",
        "on-tertiary-fixed": "#002021",
        "primary-container": "#00326b",
        "on-error-container": "#93000a",
        "inverse-surface": "#1e333c",
        "tertiary-fixed-dim": "#88d982",
        "outline-variant": "#c3c6d1",
        "surface-bright": "#f3faff",
        "inverse-on-surface": "#dff4ff",
        "on-background": "#071e27",
        "tertiary-container": "#003a3d",
        "on-secondary-fixed-variant": "#005312",
        "tertiary-fixed": "#a6eff3",
        "primary-fixed-dim": "#abc7ff",
        "on-primary-fixed-variant": "#00458f",
        "surface-container-high": "#d5ecf8",
        "on-primary-container": "#6b9bef",
        background: "#f3faff",
        "on-tertiary": "#ffffff",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        manrope: ["Manrope", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        light: "0px 20px 40px rgba(7, 30, 39, 0.06)",
        ambient: "0px 20px 40px rgba(7, 30, 39, 0.06)",
        "ambient-up": "0px -4px 20px rgba(7, 30, 39, 0.04)",
      },
    },
  },
  plugins: [],
};
